pipeline {
  agent none

  stages {
     stage ( "Build Custom Docker Image using Ansible playbook" ) {
	agent { label 'built-ini' }
	steps {
	   dir("Day5/CICD") {
		sh "ansible-playbook build-maven-docker-image-playbook.yml"
           }
	}
     }

     stage () {
	steps {
	   agent { label 'docker-slave-jenkins' }
	   dir("Day5/CICD/CRM") {
		sh "mvn compile"
           }
	}
     }

     stage () {
	steps {
	   agent { label 'docker-slave-jenkins' }
	   dir("Day5/CICD/CRM") {
		sh "mvn test"
           }
	}
     }

     stage () {
	steps {
	   agent { label 'docker-slave-jenkins' }
	   dir("Day5/CICD/CRM") {
		sh "mvn package"
           }
	}
     }

     stage () {
	steps {
	   agent { "docker-slave-jenkins" }
	   dir("Day5/CICD/CRM") {
		sh "mvn install"
           }
	}
     }


  }

}
