pipeline {
  agent none

  stages {
     stage ( "Stage 1 - Build Custom Docker Image using Ansible playbook" ) {
	agent { label 'built-in' }
	steps {
	   dir("Day5/CICD") {
		sh "ansible-playbook build-maven-docker-image-playbook.yml"
           }
	}
     }

     stage ( "Stage 2 - compile" ) {
	steps {
	   agent { label 'docker-slave-jenkins' }
	   dir("Day5/CICD/CRM") {
		sh "mvn compile"
           }
	}
     }

     stage ( "Stage 3 - test" ) {
	steps {
	   agent { label 'docker-slave-jenkins' }
	   dir("Day5/CICD/CRM") {
		sh "mvn test"
           }
	}
     }

     stage ( "Stage 4 - package" ) {
	steps {
	   agent { label 'docker-slave-jenkins' }
	   dir("Day5/CICD/CRM") {
		sh "mvn package"
           }
	}
     }

     stage ( "Stage 5 - install" ) {
	steps {
	   agent { "docker-slave-jenkins" }
	   dir("Day5/CICD/CRM") {
		sh "mvn install"
           }
	}
     }
  }
}
