- name: This playbook will install nginx, configures web root folder and deploys a custom html page in Ubuntu and CentOS
  hosts: all 

  vars_files:
  - nginx-vars.yml

  tasks:
  - include: "install-nginx-{{ansible_distribution | lower}}.yml"
  - include: common-nginx-tasks.yml
  - include: "configure-nginx-{{ansible_distribution|lower}}.yml"
  - include: "restart-nginx-{{ansible_distribution|lower}}.yml"
